lsコマンドを作る1を実施
nishibr/ruby-practices pull request #4
Opened 2023-10-15 15:47 UTC by nishibr

lsコマンド（オプションなし）のプログラムを作成しました。ご確認お願いいたします。

2023-10-21 16:14 UTC, u1tnk requested changes

2023-10-21 16:14 UTC, u1tnk commented on 04.ls/ls.rb
> +NUMBER_OF_COL = 3
NUMBER_OFが若干冗長な割に COLは省略しています。 

[プログラミング初心者は変数名やメソッド名を略さない方がいいよ、という話 - give IT a try](https://blog.jnito.com/entry/2020/10/20/092724)

こちら参考に無理に略さないようにしましょう。

なので `COLUMN_LENGTH` あたりがオススメです。

2023-10-21 16:14 UTC, u1tnk commented on 04.ls/ls.rb
> +target_dir = '*'
これも定数で良さそう。

2023-10-21 16:14 UTC, u1tnk commented on 04.ls/ls.rb
> +  Dir.glob(target_dir)
ここの target_dirは引数で渡されるので変数で良いのですが、メソッドの内外で同じ変数名を使っているとどちらを参照しているか混乱するので良くないです。

2023-10-21 16:14 UTC, u1tnk commented on 04.ls/ls.rb
> +def output(file_list)
細かいところですが、ruby界隈では `_list` / `_array` などは使わず、複数形にします。
慣習に従うのは読みやすさの上で大事なので合わせるようにしてください。

2023-10-21 16:14 UTC, u1tnk commented on 04.ls/ls.rb
> +      print file_list[number_of_row * j + i].ljust(11) if !file_list[number_of_row * j + i].nil?
「ターミナルの幅は考慮に入れなくて良い」という部分でこの 11にしていると思うのですが、さすがに固定値は良くないです。ファイル名が11を超えることがありますので。
表示したいファイル名の長さの最大のものに合わせてレイアウトするようにしてください。
削除するので今回は不要ですが、11などの意味のある数値を使うときは定数にするようにしましょう。

2023-10-22 05:40 UTC, nishibr commented on 04.ls/ls.rb
> +NUMBER_OF_COL = 3
確かに何のことなのかわからないですね..
`COLUMN_LENGTH` に修正しました！

2023-10-22 05:41 UTC, nishibr commented on 04.ls/ls.rb
> +target_dir = '*'
定数にしました。

2023-10-22 05:46 UTC, nishibr commented on 04.ls/ls.rb
> +  Dir.glob(target_dir)
変数名の使いまわしは混乱を招くのでしないようにします！

2023-10-22 05:56 UTC, nishibr commented on 04.ls/ls.rb
> +      print file_list[number_of_row * j + i].ljust(11) if !file_list[number_of_row * j + i].nil?
> 「ターミナルの幅は考慮に入れなくて良い」という部分でこの 11にしていると思うのですが、さすがに固定値は良くないです。ファイル名が11を超えることがありますので。

ファイル名の最大のものに合わせるように修正しました。

> 削除するので今回は不要ですが、11などの意味のある数値を使うときは定数にするようにしましょう。

承知しました！

2023-10-22 06:15 UTC, nishibr commented on 04.ls/ls.rb
> +def output(file_list)
慣れるまでは、命名規則や慣習などを確認したうえで命名することを徹底します。

2023-10-22 16:20 UTC, u1tnk requested changes

2023-10-22 16:20 UTC, u1tnk commented on 04.ls/ls.rb
> +  max_file_space = calculate_max_file_space(files)
これは全ファイルの最大ではなく、一列の最大にしましょう。

2023-10-22 16:20 UTC, u1tnk commented on 04.ls/ls.rb
> +      print files[number_of_row * j + i].ljust(max_file_space) if !files[number_of_row * j + i].nil?
まず `if !`  は rubyでは `unless`と書きます。
なので unlessにすれば良いかというところですが、ここでは `nil?` をチェックしています。rubyでは nil/false以外はほぼtrue扱いなので

`if files[number_of_row * j + i]`  

で大丈夫です。

ちなみに後の話ですが、 Railsでは ここを明示的に書きたい！という需要の為に `if files[number_of_row * j + i].present?` などと書くことができるようrubyを拡張しています。今は使えませんが参考まで。

2023-10-25 15:40 UTC, u1tnk approved these changes

2023-10-26 02:15 UTC, merged