lsコマンドを作る2を実施
nishibr/ruby-practices pull request #5
Opened 2023-10-26 08:17 UTC by nishibr

lsコマンドを作る2を実施しました。ご確認よろしくお願いいたします。

2023-10-26 17:11 UTC, u1tnk requested changes

2023-10-26 17:11 UTC, u1tnk commented on 04.ls/ls.rb
> +  options = set_options
main関数で options とすると ls全体のオプションに見えます。また、 ここで作るoptionは fetch_filesでしか使わないものなので fetch_files内で実行して良いと思います。

2023-10-27 13:01 UTC, nishibr commented on 04.ls/ls.rb
> +  options = set_options
レビューありがとうございます。そのように修正しました！

2023-10-29 14:13 UTC, u1tnk requested changes

2023-10-29 14:13 UTC, u1tnk commented on 04.ls/ls.rb
> +  options = set_options
指摘がわかりづらかったかもしれませんが、 前回の指摘は以下の二点を指摘していて、前者が対応されていないようなのでお願いします。

- set_optionsというメソッド自体の名前の範囲が大きすぎて誤解を招く
- set_optionsを fetch_filesで呼んだ方が良い

2023-10-30 15:05 UTC, nishibr commented on 04.ls/ls.rb
> +  options = set_options
レビューありがとうございます。指摘内容が正しく把握できていなくて申し訳ありません。
前者の方の指摘を取り込みました。ご確認よろしくお願いいたします。

2023-10-30 16:04 UTC, u1tnk requested changes

2023-10-30 16:04 UTC, u1tnk commented on 04.ls/ls.rb
> +  received_ls_options['a'] ? File::FNM_DOTMATCH : 0
ちょっと意図が違っています。

`File::FNM_DOTMATCH : 0` これを返すということは これは ls_optionsといおうLSプログラムのオプションではなく fetch_files専用のオプションを返すメソッドになっていますのでその名前にして欲しいです。

次の課題で別のオプションの対応をすること、最後に複数のオプションを実装することも考慮に入れましょう。

2023-10-30 23:04 UTC, nishibr commented on 04.ls/ls.rb
> +  received_ls_options['a'] ? File::FNM_DOTMATCH : 0
ご確認ありがとうございます。修正前に以下2点質問になります。
> File::FNM_DOTMATCH : 0 これを返すということは これは ls_optionsといおうLSプログラムのオプションではなく fetch_files専用のオプションを返すメソッドになっていますのでその名前にして欲しいです。
File::FNM_DOTMATCH : 0 はfetch_filesメソッド内のDir.globの引数として渡している以外の用途がないので、メソッド名ももっと限定的な命名のほうが良いという理解で大丈夫でしょうか？
> 次の課題で別のオプションの対応をすること、最後に複数のオプションを実装することも考慮に入れましょう。
parse_received_ls_optionsメソッド内で別のオプションの判定を追加していくイメージだったので汎用的なメソッド名にしていますが、こちら認識違いますでしょうか？

2023-10-31 16:15 UTC, u1tnk commented on 04.ls/ls.rb
> +  received_ls_options['a'] ? File::FNM_DOTMATCH : 0
>File::FNM_DOTMATCH : 0 はfetch_filesメソッド内のDir.globの引数として渡している以外の用途がないので、メソッド名ももっと限定的な命名のほうが良いという理解で大丈夫でしょうか？

はい、そうです。

> parse_received_ls_optionsメソッド内で別のオプションの判定を追加していくイメージだったので汎用的なメソッド名にしていますが、こちら認識違いますでしょうか？

そういう内容ならその名前で大丈夫ですが、 `File::FNM_DOTMATCH : 0` を返しているのでそういう意図は無いのかな？と思って指摘しました。
返り値は複数返すことも無理ではありませんが、そうであれば現段階でその構造にする必要がある(例えばhashにするとか)し、全体のオプションの判定に `File::FNM_DOTMATCH` などのファイル取得の実装の一部のような値が入ることも違和感があるので。

2023-11-01 02:22 UTC, nishibr commented on 04.ls/ls.rb
> +  received_ls_options['a'] ? File::FNM_DOTMATCH : 0
ご確認ありがとうございます。
次のプラクティス3で実施するrオプションも、プラクティス2のaオプションと同様に`Dir.glob()`の引数次第で取得結果が変わる（※rオプションの場合だと逆順にできる）想定をしていたのでparse_received_ls_optionsメソッドに集約するような作りにしていましたが、調べてみたところ無理そうですね。
なので、parse_received_ls_optionsメソッドはaオプション専用のメソッドとしてメソッド名を変更しようと思います。

※プラクティス3のイメージ
```
  received_ls_options = ARGV.getopts('a')
  received_ls_options['a'] ? File::FNM_DOTMATCH : 0
```
⇓ 変更
```
  received_ls_options = ARGV.getopts('a', 'r')   #追加
  received_ls_options['a'] ? File::FNM_DOTMATCH : 0
  received_ls_options['r'] ? <逆順で取得するオプション> : 0    #追加
```

2023-11-01 16:03 UTC, u1tnk requested changes

2023-11-01 16:03 UTC, u1tnk commented on 04.ls/ls.rb
> +  received_a_option['a'] ? File::FNM_DOTMATCH : 0
`received_a_option['a']` は aが重複して読みづらいですね。
received もあっても無くても良さそうです。

2023-11-01 16:09 UTC, u1tnk commented on 04.ls/ls.rb
> +  received_a_option['a'] ? File::FNM_DOTMATCH : 0
細かい名前にこだわり過ぎでは？
と思われそうなので補足しますと名前付けはプログラミングでとても大事なもので、rubyの 作者Matzの座右の銘も 「名前重要」です。

私がFBC生向けに書いたブログ記事もありますので一読頂けると嬉しいです。

https://u1tnk.github.io/blog/2022/12/04/naming_variable/

2023-11-02 03:19 UTC, nishibr commented on 04.ls/ls.rb
> +  received_a_option['a'] ? File::FNM_DOTMATCH : 0
記事の連携ありがとうございます。大変勉強になりました🙇‍♂️
> 「そのプログラムを読む人全員が中身を推測でき、読みやすく書きやすい簡潔な名前であること」

上記は常に意識して命名しようと思います。

2023-11-02 10:21 UTC, u1tnk approved these changes
良いと思います！
だいぶシンプルになりましたね。

2023-11-08 06:27 UTC, merged