lsコマンドを作る3を実施
nishibr/ruby-practices pull request #6
Opened 2023-11-08 06:30 UTC by nishibr

lsコマンドを作る3を実施しました。ご確認よろしくお願いいたします。

2023-11-08 13:59 UTC, u1tnk requested changes

2023-11-08 13:59 UTC, u1tnk commented on 04.ls/ls.rb
> +  elsif r_option?
このロジックだと aとr両方指摘したときに aのみになってしまいますね

2023-11-08 14:36 UTC, nishibr commented on 04.ls/ls.rb
> +  elsif r_option?
ご確認ありがとうございます。
その点ですが、プラクティスの説明に以下のように記載されているので、rオプションのみの実装しなくてはいけないという解釈したのですが間違っていますでしょうか？
> 前回のプラクティスで実装した-aオプションは実装しなくてよいです。（このシリーズ最後のプラクティスで全部合体させませす）

もしくは、aオプションの処理部分をコメントアウトしてrオプションのみ実装するイメージでしょうか？

2023-11-09 15:25 UTC, u1tnk commented on 04.ls/ls.rb
> +  elsif r_option?
以下のどちらかを想定しています。

- aとrを両方対応する
    - このパターンで全部増やしていくと プラクティス4と5が一緒になりますが、それで大丈夫でう。
- rのみを対応する

でrのみを対応する場合はコメントアウトとかでは無くプラクティス1から新しくブランチを作る方法を想定しています。
プラクティス1のPRからブランチを調べれば…と思ったんですが、同じブランチ名でやってるんですね 😓 
今後はブランチ名は使いまわさず毎回新しいものを使うと良いですね。
とはいえ https://github.com/nishibr/ruby-practices/pull/4/commits には ls1のコミットを残ってるのでここから復元はできます。gitの練習がてらやってみるのも良いかと思います。

2023-11-09 15:56 UTC, u1tnk commented on 04.ls/ls.rb
> +  elsif r_option?
補足しておくと、現状だと、aとrが両方あってちゃんと動いていれば良いですが、不完全な状態なので修正して欲しいということです 🙏

2023-11-09 16:28 UTC, nishibr commented on 04.ls/ls.rb
> +  elsif r_option?
ご回答ありがとうございます。
プラクティスの説明に「ls2〜5は、ls1と同じファイルを編集するようにしてください」と記載されているのを見落としておりました🙇‍♂️なので、aオプションは実装しなくてよいですと記載されてたんですね。。。（もう実装されているのになんでだろうと思っておりました。）
今回はls2のほうでls1のバグを改修したため、aとrを両方対応する(増やしてく)パターンで実施しようと思います。
commitのハッシュから戻すやり方は、今後どこかでしくじったときなどに参考にさせていただきます🙇‍♂️

2023-11-10 07:23 UTC, nishibr commented on 04.ls/ls.rb
> +  elsif r_option?
指摘していただいた点を修正いたしました。
オプションの判定部分ですが、`ARGV.include?`だと「-ar」のように繋げて指定された場合の対応が難しかったので、`ARGV.getopts` を使うように変更しています🙇‍♂️
ご確認よろしくお願いいたします。

2023-11-10 14:51 UTC, u1tnk requested changes
両対応の部分については大丈夫です！
コメントした部分ご確認ください 🙏

2023-11-10 14:51 UTC, u1tnk commented on 04.ls/ls.rb
> +LS_OPTIONS = ARGV.getopts('a', 'r') # 受け取り可能なlsコマンドのオプション
引数を受け取るのは状況によって違うので定数じゃなくて変数の方が良いですね。
あと、LSプログラムなので OPTIONSだけで良いかなと。何のオプションか分かりづらいと思ったんだと思いますが、何も無いと一番上位と思うのは自然なので無くて良いかなと。
もし付けるとしても main_options とかの方が良いかなと。

2023-11-11 15:24 UTC, u1tnk approved these changes

2023-11-18 18:06 UTC, merged