lsコマンドを作る4を実施
nishibr/ruby-practices pull request #7
Opened 2023-11-18 18:08 UTC by nishibr

lsコマンドを作る4を実施いたしました。ご確認よろしくお願いいたします。

2023-11-19 16:05 UTC, u1tnk requested changes
大体良さそうですね！

細かめのところコメントしたので確認お願いします。

2023-11-19 16:05 UTC, u1tnk commented on 04.ls/ls.rb
> +  case file_mode_number[2]
コードを見たところ

> long_format_mode[8] == 'x'

じゃないと変更しないってことですよね？
そうであれば先に これをチェックして x じゃなければreturnしてしまうとその後がシンプルになりますね。

2023-11-19 16:05 UTC, u1tnk commented on 04.ls/ls.rb
> +  sorted_short_format = sort_short_format(files)
short_formatはメソッド名で分かるのでメソッド内で `sorted_short_format` というのは重複していますし、実体はファイル情報なのでちょっと名前良くないですね。 long_formatも同様です。

2023-11-20 13:40 UTC, nishibr commented on 04.ls/ls.rb
> +  case file_mode_number[2]
ご確認ありがとうございます。
ここは`long_format_mode[8] == 'x'`なら`t`にそれ以外なら`T`にするので、修正不要かと思うのですがどうでしょうか。

2023-11-20 14:40 UTC, u1tnk approved these changes

2023-11-20 14:40 UTC, u1tnk commented on 04.ls/ls.rb
> +  case file_mode_number[2]
ああー、なるほど、ちょっと勘違いしてましたね。了解です。大丈夫です 🙆‍♀️

2024-03-14 06:48 UTC, merged